spring:
  application:
    name: TALENTAI_CONFIG
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: classpath:/config # Example search location for native profile
        bootstrap: true
server:
 port: 8071

